<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Robert Peele</Authors>
    <Description>F# type provider for Rezoom.SQL.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/rspeele/Rezoom.SQL</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rspeele/Rezoom.SQL</RepositoryUrl>
    <PackageReleaseNotes>1.1.0: adds support for custom user defined types.</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Watcher.fs" />
    <Compile Include="UserModelCache.fs" />
    <Compile Include="CompileTimeColumnMap.fs" />
    <None Include="ProvidedTypes-LICENSE.md" />
    <Compile Include="ProvidedTypes.fsi" />
    <Compile Include="ProvidedTypes.fs" />
    <Compile Include="DocStrings.fs" />
    <Compile Include="InterfaceImpls.fs" />
    <Compile Include="TypeGeneration.fs" />
    <Compile Include="Provider.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="8.0.401" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rezoom.SQL.Compiler\Rezoom.SQL.Compiler.fsproj" />
    <ProjectReference Include="..\Rezoom.SQL.Mapping\Rezoom.SQL.Mapping.fsproj" />
  </ItemGroup>

</Project>
