<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SQLFiddle</RootNamespace>
    <AssemblyName>SQLFiddle</AssemblyName>
    <IsPackable>false</IsPackable>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Model.fs" />
    <Compile Include="Persistence.fsi" />
    <Compile Include="Persistence.fs" />
    <Compile Include="Domain.fsi" />
    <Compile Include="Domain.fs" />
    <Compile Include="Execution.fs" />
    <None Include="App.config" />
    <EmbeddedResource Include="V1.model.sql" />
    <EmbeddedResource Include="rzsql.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="8.0.401" />
    <PackageReference Include="Rezoom" Version="1.1.0" />
    <PackageReference Include="Rezoom.SQL.Compiler" Version="0.5.0" />
    <PackageReference Include="Rezoom.SQL.Mapping" Version="0.5.0" />
    <PackageReference Include="Rezoom.SQL.Provider" Version="0.7.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>

</Project>
