namespace Rezoom.SQL.Mapping

type ColumnId = int

// An EntityReader<Foo> is a way of building a Foo from a SQL result set.
// Note that, despite the name, 'a doesn't have to be a singular database entity like `User`.
// It can be a collection type too. In fact most of the time when we process a result set
// we will want an array of Users. That is accomplished by an EntityReader<User[]>.
// The implementation of any given EntityReader<'a> is built once (per custom primitive mapping context)
// at runtime and cached in StaticEntityReaderTemplate.fs.
// Those implementations can recursively use other EntityReaders.
// For example the implemention for EntityReader<User[]>
// creates a private dictionary <(user id), EntityReader<User>>. Each time it .Read()s a row,
// it passes it down to the appropriate sub-reader based on the ID columns, and if one is not
// found, it makes a new one using ReaderTemplate<User>.Template(...).CreateReader() and adds
// it to its dictionary.

// EntityReader instances are not allocated for individual primitive columns within a composite, however.
// Primitive columns get implemented inline directly on the EntityReader<User>.
// This prevents us from having a zillion allocations of new EntityReaders for every user we try to process.
// When looking at the *ColumnGenerator.fs files, remember that they don't build a full EntityReader,
// they define the parts of its various methods that will relate to a single column or nav-property.
// The final .Read() and .ProcessColumns()  methods end up being generated by gluing together chunks of IL
// coming from *all* the columns in the composite type.

[<AbstractClass>]
type EntityReader() =
    /// Called once at beginning of processing to inform the EntityReader
    /// of the shape of the rows it's going to be given. This is the only
    /// time it gets to know what the name is of each column, when reading rows it
    /// has to access column values by integer index for XTreme 1337 h4ck3r Speed.
    abstract member ProcessColumns : ColumnMap -> unit
    /// Called once per row to supply the reader with data. Reader tracks internal state
    /// it will eventually spit out with .ToEntity() when all rows have been processed.
    abstract member Read : Row -> unit
    /// Used to help nav-properties that are bidirectional. If we have a User
    /// who has many Comments, that we are loading with our SQL MANY(...) nav prop feature,
    /// we may want each Comment to have a User property so the nav can be consumed either way.
    /// That User property pointing "back up" the hierarchy is what SetReverse is for.
    /// The parent EntityReader for User calls SetReverse(reverseColumnId, self) on its children.
    abstract member SetReverse : ColumnId * obj -> unit

[<AbstractClass>]
type EntityReader<'ent>() =
    inherit EntityReader()
    /// Used by collection-type entity readers. The reader for `User array` internally
    /// creates another new EntityReader<User>() every time it finishes building one User
    /// and starts building the next. Rather than have the next reader ProcessColumns again
    /// to know what is going on (expensive), we have the previous reader bring it up to speed
    /// by calling previousUserReader.ImpartKnowledgeToNext(nextUserReader).
    abstract member ImpartKnowledgeToNext : EntityReader<'ent> -> unit
    /// Spit out the entity we have built from the rows we have consumed.
    abstract member ToEntity : unit -> 'ent

/// No-op EntityReader that wraps an already-constructed entity.
/// ToEntity returns the wrapped value. Used by CompositeColumnGenerator's
/// generated SetReverse methods to install a parent reference into a child reader's backreference col slot.
type ObjectEntityReader<'ent>(ent : 'ent) =
    inherit EntityReader<'ent>()
    override __.ImpartKnowledgeToNext(_) = ()
    override __.ProcessColumns(_) = ()
    override __.Read(_) = ()
    override __.SetReverse(_, _) = ()
    override __.ToEntity() = ent

[<AbstractClass>]
type EntityReaderTemplate<'ent>() =
    abstract member CreateReader : unit -> 'ent EntityReader