namespace Rezoom.SQL.Mapping
open System
open System.Reflection
open System.Collections.Concurrent
open Rezoom.SQL.Mapping.FreezeDry

/// Runtime mechanism for a user primitive's ToPrimitive conversion.
/// This is used by input parameters to Command() methods generated by the type provider.
/// By doing the reflection and codegen at runtime (once, then cached), we can
/// avoid a LOT of hairy complexity trying to make type provider generated code
/// work. Generative type providers have many, many pitfalls when trying to build
/// real method logic rather than just thin wrappers around a runtime library.
/// Even the thin wrappers aren't always easy to get working in both Visual Studio and dotnet CLI.
module RuntimeUserConvert =
    // Cache an obj -> obj ToPrimitive invoker, keyed by the whole freeze-dried
    // record. It's a plain F# record (structural equality), so this keys on every
    // field buildInvoker reads — including the assembly names, which is what
    // actually disambiguates two models that map the same user-type full name to
    // different DLLs. (A name-only key would alias those together.)
    // Currently these invokers are pure reflection, not doing any codegen with LicenseToCIL.
    // Don't think it's worth it for converting a few parameters per command. But could swap that in later if needed.
    let private invokerCache = ConcurrentDictionary<FreezeDriedUserPrimitiveType, obj -> obj>()

    let private buildInvoker (fd : FreezeDriedUserPrimitiveType) : obj -> obj =
        let clrAsm = Assembly.Load(fd.UserCLRTypeAssemblyName)
        let clrTy = clrAsm.GetType(fd.UserCLRTypeFullName, throwOnError = true)
        if fd.ToPrimitiveIsInstanceMethod then
            let m =
                clrTy.GetMethod
                    ( fd.ToPrimitiveMethodName
                    , BindingFlags.Instance ||| BindingFlags.Public, null, [||], null )
            if isNull m then
                failwithf "RuntimeUserConvert: instance ToPrimitive '%s' not found on %s"
                    fd.ToPrimitiveMethodName fd.UserCLRTypeFullName
            fun (v : obj) -> m.Invoke(v, [||])
        else
            let decAsm =
                if fd.DeclaringAssemblyName = fd.UserCLRTypeAssemblyName then clrAsm
                else Assembly.Load(fd.DeclaringAssemblyName)
            let decTy =
                if fd.DeclaringTypeFullName = fd.UserCLRTypeFullName && obj.ReferenceEquals(decAsm, clrAsm)
                then clrTy
                else decAsm.GetType(fd.DeclaringTypeFullName, throwOnError = true)
            let m =
                decTy.GetMethod
                    ( fd.ToPrimitiveMethodName
                    , BindingFlags.Static ||| BindingFlags.Public, null, [| clrTy |], null )
            if isNull m then
                failwithf "RuntimeUserConvert: static ToPrimitive '%s' not found on %s"
                    fd.ToPrimitiveMethodName fd.DeclaringTypeFullName
            fun (v : obj) -> m.Invoke(null, [| v |])

    /// Convert a (possibly Option-wrapped) user primitive value to its underlying
    /// primitive, boxed. None/null returns null — the caller maps that to DBNull.
    let toPrimitive (fd : FreezeDriedUserPrimitiveType) (value : obj) : obj =
        if isNull value then null else
        // Unwrap FSharpOption.
        let value =
            let t = value.GetType()
            if t.IsGenericType && t.GetGenericTypeDefinition() = typedefof<_ option>
            then t.GetProperty("Value").GetValue(value)
            else value
        if isNull value then null else
        let invoker =
            let builder = Func<FreezeDriedUserPrimitiveType, obj -> obj>(fun fd -> buildInvoker fd)
            invokerCache.GetOrAdd(fd, builder)
        invoker value

    type RowTypeConverter() =
        static member ToOptionalRowType<'t> (value : obj) : 't option =
            if isNull value then None else
            let value =
                let t = value.GetType()
                if t.IsGenericType && t.GetGenericTypeDefinition() = typedefof<_ option>
                then t.GetProperty("Value").GetValue(value)
                else value
            match value with
            | :? 't as expectedType -> Some expectedType
            | _ -> None